apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloud-task-manager-monitoring-allow
  namespace: cloud-devops
spec:
  podSelector:
    matchLabels:
      app: cloud-task-manager
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 80