apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-task-manager-pvc
  namespace: cloud-devops

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: standard

  resources:
    requests:
      storage: 1Gi